# x-logging: &default-logging
#   driver: "local"
#   options:
#     max-size: "20m"
#     max-file: "3"

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: "50m"
    max-file: "10"
    keep-file: "true"


services:
  mcim_schedule_sync:
    container_name: mcim_schedule_sync
    image: mcim_schedule_sync
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./config.json:/app/config.json
    command: >
      sh -c "python start.py"
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    network_mode: host