x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "3"

services:
  mcim_schedule_sync:
    container_name: mcim_schedule_sync
    image: mcim_schedule_sync
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - /opt/mcim_sync/config.json:/config.json
    command: >
      sh -c "python start.py"
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    network_mode: host