name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit test
    env:
        CONFIG: ${{ secrets.CONFIG }} # 配置文件
        CHAT_ID: ${{ secrets.CHAT_ID }} # 测试 telegram 通知
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0

      - name: Install dependencies
        run: |
          just mongodb-tool-install
          just redis-tool-install
          just ci-install

      - name: Run unit tests
        run: |
          just ci-test